In [92]:
import pandas as pd
import random
from faker import Faker
from pathlib import Path

fake = Faker()

Faker.seed(42)
random.seed(42)

# Paramaterized code

BASE_PATH = Path("../data/raw")

PLM_PATH = BASE_PATH / "plm"
MES_PATH = BASE_PATH / "mes"

PLM_PATH.mkdir(parents=True, exist_ok=True)
MES_PATH.mkdir(parents=True, exist_ok=True)

NUM_PRODUCTS = 100
NUM_BOM = 700
NUM_ECN = 150
NUM_MACHINE_LOGS = 3000
NUM_ORDERS = 500
NUM_DOWNTIME = 300

In [63]:
# Generate Product IDs

product_ids = []

for i in range(1, NUM_PRODUCTS + 1):
    product_ids.append(f"PROD-{i:03}")

In [64]:
product_names = [
    "Widget Alpha",
    "Widget Beta",
    "Widget Gamma",
    "Widget Delta",
    "Gear Assembly",
    "Drive Shaft",
    "Bearing Housing",
    "Brake Disc",
    "Clutch Plate",
    "Engine Block",
    "Cylinder Head",
    "Axle Shaft",
    "Pulley Wheel",
    "Rotor Assembly",
    "Stator Unit",
    "Control Panel",
    "Hydraulic Pump",
    "Valve Body",
    "Roller Bearing",
    "Flexible Coupling",
    "Flywheel",
    "Crankshaft",
    "Piston Kit",
    "Camshaft",
    "Oil Pump",
    "Fuel Injector",
    "Timing Belt",
    "Cooling Fan",
    "Radiator",
    "Air Filter",
    "Exhaust Manifold",
    "Turbocharger",
    "Starter Motor",
    "Alternator",
    "Wheel Hub",
    "Steering Knuckle",
    "Suspension Arm",
    "Brake Caliper",
    "Shock Absorber",
    "Transmission Case",
    "Differential Gear",
    "Planetary Gear",
    "Universal Joint",
    "Seal Ring",
    "O-Ring",
    "Mounting Flange",
    "Fastener Kit",
    "Hex Bolt",
    "Lock Nut",
    "Flat Washer",
    "Chain Sprocket",
    "Roller Chain",
    "Linear Guide",
    "Servo Motor",
    "Stepper Motor",
    "PLC Module",
    "Sensor Module",
    "Pressure Sensor",
    "Temperature Sensor",
    "Flow Meter",
    "Solenoid Valve",
    "Electric Actuator",
    "Control Valve",
    "Hydraulic Cylinder",
    "Pneumatic Cylinder",
    "Air Compressor",
    "Vacuum Pump",
    "Heat Exchanger",
    "Boiler Tube",
    "Conveyor Roller",
    "Conveyor Belt",
    "Mixer Blade",
    "Impeller",
    "Filter Housing",
    "Spray Nozzle",
    "Manifold Block",
    "Electrical Connector",
    "Terminal Block",
    "Fuse Box",
    "Power Supply Unit",
    "Transformer Core",
    "Cooling Jacket",
    "Fan Blade",
    "Motor Shaft",
    "Housing Cover",
    "Gear Wheel",
    "Rack Gear",
    "Pinion Gear",
    "Support Bracket",
    "Mounting Plate",
    "Pipe Clamp",
    "Door Frame",
    "Chassis Frame",
    "Base Plate",
    "Machine Guard",
    "Inspection Cover",
    "Lubrication Unit",
    "Tool Holder",
    "Cutting Head",
    "Spindle Assembly"
]

In [65]:
product_data = []

for i in range(NUM_PRODUCTS):

    file_name = product_names[i].lower().replace(" ", "_")
    cad_file = f"{file_name}_v1.step"

    row = {
        "product_id": product_ids[i],
        "product_name": product_names[i],
        "design_release_date": fake.date_between(
            start_date="-3y",
            end_date="today"
        ),
        "CAD_file_ref": cad_file
    }

    product_data.append(row)

product_df = pd.DataFrame(product_data)

In [66]:
product_df.head()

  product_id   product_name design_release_date           CAD_file_ref
0   PROD-001   Widget Alpha          2026-04-12   widget_alpha_v1.step
1   PROD-002    Widget Beta          2024-01-12    widget_beta_v1.step
2   PROD-003   Widget Gamma          2023-08-31   widget_gamma_v1.step
3   PROD-004   Widget Delta          2024-09-23   widget_delta_v1.step
4   PROD-005  Gear Assembly          2024-08-07  gear_assembly_v1.step

In [67]:
product_df.to_csv(
    PLM_PATH / "product_metadata.csv",
    index=False
)

print("product_metadata.csv created successfully")
print(product_df.shape)

product_metadata.csv created successfully
(100, 4)

In [68]:
print("Current Working Directory:")
print(Path.cwd())

print("\nPLM Path:")
print(PLM_PATH.resolve())

Current Working Directory:
D:\Internship\mes-plm-poc\notebooks

PLM Path:
D:\Internship\mes-plm-poc\data\raw\plm

In [69]:
print(NUM_PRODUCTS)
print(len(product_names))
print(len(product_ids))

100
100
100

In [70]:
#BOM.CSV
product_df = pd.read_csv(PLM_PATH / "product_metadata.csv")
product_df.head()

  product_id   product_name design_release_date           CAD_file_ref
0   PROD-001   Widget Alpha          2026-04-12   widget_alpha_v1.step
1   PROD-002    Widget Beta          2024-01-12    widget_beta_v1.step
2   PROD-003   Widget Gamma          2023-08-31   widget_gamma_v1.step
3   PROD-004   Widget Delta          2024-09-23   widget_delta_v1.step
4   PROD-005  Gear Assembly          2024-08-07  gear_assembly_v1.step

In [71]:
components = [
    "COMP-001",
    "COMP-002",
    "COMP-003",
    "COMP-004",
    "COMP-005",
    "COMP-006",
    "COMP-007",
    "COMP-008",
    "COMP-009",
    "COMP-010",
    "COMP-011",
    "COMP-012",
    "COMP-013",
    "COMP-014",
    "COMP-015",
    "COMP-016",
    "COMP-017",
    "COMP-018",
    "COMP-019",
    "COMP-020",
    "COMP-021",
    "COMP-022",
    "COMP-023",
    "COMP-024",
    "COMP-025",
    "COMP-026",
    "COMP-027",
    "COMP-028",
    "COMP-029",
    "COMP-030"
]

versions = [
    "v1.0",
    "v1.1",
    "v2.0",
    "v2.1",
    "v3.0"
]

In [72]:
bom_data = []

versions = [
    "v1.0",
    "v1.1",
    "v2.0",
    "v2.1",
    "v3.0"
]

for product_id in product_df["product_id"]:

    # Each product will have 5 to 8 unique components
    selected_components = random.sample(components, random.randint(5, 8))

    for component in selected_components:

        row = {
            "product_id": product_id,
            "component_id": component,
            "quantity": random.randint(1, 10),
            "component_version": random.choice(versions)
        }

        bom_data.append(row)

bom_df = pd.DataFrame(bom_data)

In [73]:
bom_df.to_csv(
    PLM_PATH / "bom.csv",
    index=False
)

print("bom.csv created successfully")
print("Rows :", len(bom_df))

bom.csv created successfully
Rows : 653

In [74]:
bom_df.to_csv(
    PLM_PATH / "bom.csv",
    index=False
)

print("bom.csv created successfully")
print(bom_df.shape)

bom.csv created successfully
(653, 4)

In [75]:
print(bom_df.shape)
print()

print(bom_df.head())
print()

print(bom_df["product_id"].nunique())

(653, 4)

  product_id component_id  quantity component_version
0   PROD-001     COMP-001         2              v3.0
1   PROD-001     COMP-024         2              v3.0
2   PROD-001     COMP-009         7              v1.0
3   PROD-001     COMP-008         1              v1.0
4   PROD-001     COMP-005         4              v1.1

100

In [76]:
#ENCR.CSV
product_df = pd.read_csv(PLM_PATH / "product_metadata.csv")
product_df.head()

  product_id   product_name design_release_date           CAD_file_ref
0   PROD-001   Widget Alpha          2026-04-12   widget_alpha_v1.step
1   PROD-002    Widget Beta          2024-01-12    widget_beta_v1.step
2   PROD-003   Widget Gamma          2023-08-31   widget_gamma_v1.step
3   PROD-004   Widget Delta          2024-09-23   widget_delta_v1.step
4   PROD-005  Gear Assembly          2024-08-07  gear_assembly_v1.step

In [77]:
change_types = [
    "Design Update",
    "Material Change",
    "Dimension Change",
    "Supplier Change",
    "Quality Improvement",
    "Cost Reduction",
    "Performance Enhancement",
    "Compliance Update"
]

In [78]:
ecn_data = []

for i in range(NUM_ECN):

    row = {
        "change_id": f"ECN-{i+1:03d}",
        "product_id": random.choice(product_df["product_id"]),
        "change_type": random.choice(change_types),
        "request_date": fake.date_between(
            start_date="-2y",
            end_date="today"
        ),
       "approved_flag": random.choices(
    ["True", "False"],
    weights=[80, 20],
    k=1
)[0]
    }

    ecn_data.append(row)

ecn_df = pd.DataFrame(ecn_data)

In [79]:
ecn_df.head()

  change_id product_id        change_type request_date approved_flag
0   ECN-001   PROD-029    Material Change   2026-05-08         False
1   ECN-002   PROD-018    Supplier Change   2026-03-11          True
2   ECN-003   PROD-004     Cost Reduction   2026-03-17          True
3   ECN-004   PROD-048  Compliance Update   2024-09-04         False
4   ECN-005   PROD-071   Dimension Change   2025-01-16          True

In [80]:
ecn_df.to_csv(
    PLM_PATH / "ecn_requests.csv",
    index=False
)

print("ecn_requests.csv created successfully")
print(ecn_df.shape)

ecn_requests.csv created successfully
(150, 5)

In [81]:
print(ecn_df.shape)
print()

print(ecn_df.head())
print()

print(ecn_df.isnull().sum())

(150, 5)

  change_id product_id        change_type request_date approved_flag
0   ECN-001   PROD-029    Material Change   2026-05-08         False
1   ECN-002   PROD-018    Supplier Change   2026-03-11          True
2   ECN-003   PROD-004     Cost Reduction   2026-03-17          True
3   ECN-004   PROD-048  Compliance Update   2024-09-04         False
4   ECN-005   PROD-071   Dimension Change   2025-01-16          True

change_id        0
product_id       0
change_type      0
request_date     0
approved_flag    0
dtype: int64

In [93]:
#Machine_logs.csv
machine_ids = [
    "M01",
    "M02",
    "M03",
    "M04",
    "M05",
    "M06",
    "M07",
    "M08",
    "M09",
    "M10"
]

status_list = [
    "Running",
    "Idle",
    "Maintenance"
]

In [94]:
machine_logs = []

for i in range(NUM_MACHINE_LOGS):

    row = {
        "timestamp": fake.date_time_between(
            start_date="-1y",
            end_date="now"
        ),
        "machine_id": random.choice(machine_ids),
        "status": random.choices(
            ["Running", "Idle", "Maintenance"],
            weights=[80, 15, 5],
            k=1
        )[0],
        "cycle_time_ms": random.randint(800, 2500),
        "output_count": random.randint(1, 15),
        "defect_flag": random.choices(
            ["True", "False"],
            weights=[5, 95],
            k=1
        )[0]
    }

    machine_logs.append(row)

machine_logs_df = pd.DataFrame(machine_logs)

In [84]:
machine_logs_df.head()

,timestamp,machine_id,status,cycle_time_ms,output_count,defect_flag
0,2026-02-18 23:07:38,M02,Maintenance,1766,1,False
1,2026-05-13 20:06:19,M03,Running,2368,11,False
2,2026-05-03 23:58:27,M07,Running,1583,8,False
3,2026-04-18 10:33:21,M07,Running,2198,11,False
4,2025-10-10 15:23:14,M03,Running,1512,2,False

In [96]:
machine_logs_df.to_csv(
    MES_PATH / "machine_logs.csv",
    index=False
)

print("machine_logs.csv created successfully")
print(machine_logs_df.shape)

machine_logs.csv created successfully
(3000, 6)

In [97]:
print(machine_logs_df.shape)
print()

print(machine_logs_df.head())
print()

print(machine_logs_df.isnull().sum())

(3000, 6)

            timestamp machine_id   status  cycle_time_ms  output_count  \
0 2026-03-29 20:29:27        M02  Running           1363             4
1 2025-09-05 18:16:54        M02  Running           1916             2
2 2025-08-03 05:43:05        M01  Running           1247             4
3 2026-05-08 12:21:09        M01  Running           2266            11
4 2025-11-08 08:03:36        M07  Running           2006             5

  defect_flag
0       False
1       False
2       False
3       False
4       False

timestamp        0
machine_id       0
status           0
cycle_time_ms    0
output_count     0
defect_flag      0
dtype: int64

In [98]:
#product_orders.csv
product_df = pd.read_csv(PLM_PATH / "product_metadata.csv")
product_df.head()

  product_id   product_name design_release_date           CAD_file_ref
0   PROD-001   Widget Alpha          2026-04-12   widget_alpha_v1.step
1   PROD-002    Widget Beta          2024-01-12    widget_beta_v1.step
2   PROD-003   Widget Gamma          2023-08-31   widget_gamma_v1.step
3   PROD-004   Widget Delta          2024-09-23   widget_delta_v1.step
4   PROD-005  Gear Assembly          2024-08-07  gear_assembly_v1.step

In [99]:
production_orders = []

for i in range(NUM_ORDERS):

    start_time = fake.date_time_between(
        start_date="-1y",
        end_date="now"
    )

    duration = random.randint(1, 8)

    end_time = start_time + pd.Timedelta(hours=duration)

    planned_qty = random.randint(100, 500)

    actual_qty = planned_qty - random.randint(0, 20)

    row = {
        "order_id": f"ORD-{i+1:04d}",
        "product_id": random.choice(product_df["product_id"]),
        "start_time": start_time,
        "end_time": end_time,
        "planned_qty": planned_qty,
        "actual_qty": actual_qty
    }

    production_orders.append(row)

production_orders_df = pd.DataFrame(production_orders)

In [89]:
production_orders_df.head()

,order_id,product_id,start_time,end_time,planned_qty,actual_qty
0,ORD-0001,PROD-040,2025-11-01 11:04:31,2025-11-01 15:04:31,325,316
1,ORD-0002,PROD-049,2025-09-25 10:09:26,2025-09-25 13:09:26,197,178
2,ORD-0003,PROD-035,2026-05-23 17:28:03,2026-05-23 18:28:03,244,240
3,ORD-0004,PROD-024,2025-08-22 06:13:37,2025-08-22 11:13:37,266,266
4,ORD-0005,PROD-082,2025-11-09 05:01:51,2025-11-09 11:01:51,299,284

In [100]:
production_orders_df.to_csv(
    MES_PATH / "production_orders.csv",
    index=False
)

print("production_orders.csv created successfully")
print(production_orders_df.shape)

production_orders.csv created successfully
(500, 6)

In [101]:
print(production_orders_df.shape)
print()

print(production_orders_df.head())
print()

print(production_orders_df.isnull().sum())

(500, 6)

   order_id product_id          start_time            end_time  planned_qty  \
0  ORD-0001   PROD-014 2025-09-29 00:18:35 2025-09-29 07:18:35          244
1  ORD-0002   PROD-024 2026-04-06 08:26:23 2026-04-06 12:26:23          215
2  ORD-0003   PROD-086 2026-03-24 01:10:20 2026-03-24 06:10:20          268
3  ORD-0004   PROD-042 2026-04-30 09:23:19 2026-04-30 14:23:19          489
4  ORD-0005   PROD-075 2026-07-09 19:51:43 2026-07-10 02:51:43          291

   actual_qty
0         225
1         207
2         254
3         485
4         287

order_id       0
product_id     0
start_time     0
end_time       0
planned_qty    0
actual_qty     0
dtype: int64

In [102]:
#downtime.csv
reason_codes = [
    "Scheduled Maintenance",
    "Machine Failure",
    "Power Outage",
    "Tool Replacement",
    "Material Shortage",
    "Quality Inspection",
    "Operator Break",
    "Sensor Fault"
]

In [103]:
downtime_events = []

for i in range(NUM_DOWNTIME):

    start_time = fake.date_time_between(
        start_date="-1y",
        end_date="now"
    )

    duration = random.randint(30, 240)

    end_time = start_time + pd.Timedelta(minutes=duration)

    row = {
        "event_id": f"DT-{i+1:03d}",
        "machine_id": random.choice(machine_ids),
        "start_time": start_time,
        "end_time": end_time,
        "reason_code": random.choice(reason_codes)
    }

    downtime_events.append(row)

downtime_df = pd.DataFrame(downtime_events)

In [104]:
downtime_df.head()

,event_id,machine_id,start_time,end_time,reason_code
0,DT-001,M10,2025-12-20 11:52:51,2025-12-20 15:16:51,Sensor Fault
1,DT-002,M08,2025-10-23 23:55:32,2025-10-24 01:23:32,Machine Failure
2,DT-003,M03,2026-01-14 00:35:07,2026-01-14 01:30:07,Power Outage
3,DT-004,M10,2026-05-13 06:13:47,2026-05-13 07:16:47,Scheduled Maintenance
4,DT-005,M08,2025-11-05 05:16:33,2025-11-05 07:38:33,Quality Inspection

In [105]:
downtime_df.to_csv(
    MES_PATH / "downtime_events.csv",
    index=False
)

print("downtime_events.csv created successfully")
print(downtime_df.shape)

downtime_events.csv created successfully
(300, 5)

In [106]:
print(downtime_df.shape)
print()

print(downtime_df.head())
print()

print(downtime_df.isnull().sum())

(300, 5)

  event_id machine_id          start_time            end_time  \
0   DT-001        M10 2025-12-20 11:52:51 2025-12-20 15:16:51
1   DT-002        M08 2025-10-23 23:55:32 2025-10-24 01:23:32
2   DT-003        M03 2026-01-14 00:35:07 2026-01-14 01:30:07
3   DT-004        M10 2026-05-13 06:13:47 2026-05-13 07:16:47
4   DT-005        M08 2025-11-05 05:16:33 2025-11-05 07:38:33

             reason_code
0           Sensor Fault
1        Machine Failure
2           Power Outage
3  Scheduled Maintenance
4     Quality Inspection

event_id       0
machine_id     0
start_time     0
end_time       0
reason_code    0
dtype: int64